version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass123
      MONGO_INITDB_DATABASE: sampleDb
    volumes:
      - mongo_data:/data/db

  backend:
    build: .
    container_name: backend
    restart: always
    environment:
      MONGO_URL: mongodb://root:pass123@mongo:27017/sampleDb?authSource=admin
      PORT: 3333
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./certbot/conf:/etc/letsencrypt
    - ./certbot/www:/var/www/certbot
    depends_on:
    - backend

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot


volumes:
  mongo_data:
